//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W27_10_2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDETAI
    {
        public int MaDT { get; set; }
        public string SanPham { get; set; }
        public string MucTieu { get; set; }
        public string YeuCau { get; set; }
        public Nullable<bool> KhacCN { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SLSinhVien { get; set; }
        public Nullable<float> DiemDT { get; set; }
        public string ChuThich { get; set; }
        public string NienKhoa { get; set; }
        public Nullable<int> TruongNhom { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
        public virtual DETAI DETAI { get; set; }
    }
}
