//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W27_10_2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKY
    {
        public int MaSV { get; set; }
        public int MaCN { get; set; }
        public Nullable<int> DoUT { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CHUYENNGANH CHUYENNGANH { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
