//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W27_10_2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU_THANG
    {
        public int ThangBH { get; set; }
        public int NamBH { get; set; }
        public Nullable<int> DoanhThu_TH { get; set; }
        public Nullable<int> TongGiaSP_TH { get; set; }
        public Nullable<int> TongLuong_NV { get; set; }
    }
}
