//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W27_10_2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int MaNV { get; set; }
        public int NgayTL { get; set; }
        public Nullable<int> Luong1 { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
