//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W27_10_2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MaTK { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaSV { get; set; }
        public Nullable<int> MaGV { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
